-- =========================================================
-- SUPABASE DATABASE — MASJID KAMPUS UMS
-- Jalankan seluruh script ini di Supabase SQL Editor.
-- =========================================================

create table if not exists public.prayer_schedule (
  id bigint generated by default as identity primary key,
  prayer_date date not null,
  name text not null,
  time time not null,
  display_order int not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  category text,
  event_date date not null,
  start_time text,
  created_at timestamptz not null default now()
);

create table if not exists public.donation_accounts (
  id bigint generated by default as identity primary key,
  bank_name text not null,
  account_number text not null,
  account_name text not null,
  is_active boolean not null default true,
  display_order int not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  created_at timestamptz not null default now()
);

-- Data semua layanan masuk ke satu tabel.
-- form_data memakai JSONB supaya tiap layanan bisa mempunyai
-- field yang berbeda tanpa perlu membuat banyak tabel.
create table if not exists public.service_requests (
  id bigint generated by default as identity primary key,
  service_type text not null,
  action_type text not null,
  service_name text not null,
  form_data jsonb not null default '{}'::jsonb,
  status text not null default 'baru',
  admin_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- =========================================================
-- RLS
-- =========================================================
alter table public.prayer_schedule enable row level security;
alter table public.events enable row level security;
alter table public.donation_accounts enable row level security;
alter table public.contact_messages enable row level security;
alter table public.service_requests enable row level security;

drop policy if exists "public read prayer schedule" on public.prayer_schedule;
create policy "public read prayer schedule"
on public.prayer_schedule for select to anon, authenticated using (true);

drop policy if exists "public read events" on public.events;
create policy "public read events"
on public.events for select to anon, authenticated using (true);

drop policy if exists "public read active donation accounts" on public.donation_accounts;
create policy "public read active donation accounts"
on public.donation_accounts for select to anon, authenticated using (is_active = true);

drop policy if exists "public insert contact messages" on public.contact_messages;
create policy "public insert contact messages"
on public.contact_messages for insert to anon, authenticated
with check (true);

drop policy if exists "public insert service requests" on public.service_requests;
create policy "public insert service requests"
on public.service_requests for insert to anon, authenticated
with check (true);

-- Data pelayanan aktif bisa ditampilkan di halaman publik.
-- Hanya data yang sudah aktif/disetujui/diproses/selesai yang dibaca publik.
drop policy if exists "public read active service requests" on public.service_requests;
create policy "public read active service requests"
on public.service_requests for select to anon, authenticated
using (
  service_type in ('peminjaman-masjid', 'peminjaman-alat', 'media-partner')
  and status in ('baru', 'diproses', 'disetujui', 'ditolak', 'selesai')
);

-- Jangan buat policy UPDATE/DELETE untuk anon.
-- Data layanan sebaiknya dikelola melalui akun admin/server-side.

-- =========================================================
-- CONTOH DATA
-- =========================================================
insert into public.events (title, description, category, event_date, start_time)
values
('Kajian Tafsir Al-Qur''an', 'Kajian rutin untuk memahami pesan Al-Qur''an.', 'Kajian', current_date + 3, '19:30'),
('Tahsin Al-Qur''an', 'Pembelajaran bacaan Al-Qur''an untuk civitas dan masyarakat.', 'Pendidikan', current_date + 5, '16:30'),
('Santunan Yatim', 'Program berbagi dan silaturahmi bersama anak-anak yatim.', 'Sosial', current_date + 10, '09:00');

insert into public.donation_accounts (bank_name, account_number, account_name, display_order)
values
('Bank Syariah Indonesia', '7123456789', 'Masjid Kampus UMS', 1),
('BCA Syariah', '1234567890', 'Masjid Kampus UMS', 2);

insert into public.prayer_schedule (prayer_date, name, time, display_order)
values
(current_date, 'Subuh', '04:47', 1),
(current_date, 'Dzuhur', '12:08', 2),
(current_date, 'Ashar', '15:27', 3),
(current_date, 'Maghrib', '18:12', 4),
(current_date, 'Isya', '19:22', 5);


-- =========================================================
-- ADMIN AUTHORIZATION
-- 1) Buat user admin di Supabase Dashboard:
--    Authentication > Users > Add user
-- 2) Salin UUID user tersebut.
-- 3) Masukkan UUID ke public.admin_users.
-- =========================================================

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'admin',
  created_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;

-- Hapus policy lama bila script dijalankan ulang.
drop policy if exists "admins can read own admin record" on public.admin_users;
create policy "admins can read own admin record"
on public.admin_users for select to authenticated
using (user_id = (select auth.uid()));

-- Fungsi ini hanya mengembalikan true/false; data admin_users tidak dibuka ke anon.
create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = ''
stable
as $$
  select exists (
    select 1
    from public.admin_users
    where user_id = (select auth.uid())
      and role = 'admin'
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

-- =========================================================
-- RLS: Admin dapat melihat/mengelola data internal.
-- Pengunjung tetap hanya dapat INSERT pengajuan/kontak.
-- =========================================================

drop policy if exists "admins can read service requests" on public.service_requests;
create policy "admins can read service requests"
on public.service_requests for select to authenticated
using ((select public.is_admin()));

drop policy if exists "admins can update service requests" on public.service_requests;
create policy "admins can update service requests"
on public.service_requests for update to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "admins can delete service requests" on public.service_requests;
create policy "admins can delete service requests"
on public.service_requests for delete to authenticated
using ((select public.is_admin()));

drop policy if exists "admins can read contact messages" on public.contact_messages;
create policy "admins can read contact messages"
on public.contact_messages for select to authenticated
using ((select public.is_admin()));

drop policy if exists "admins can delete contact messages" on public.contact_messages;
create policy "admins can delete contact messages"
on public.contact_messages for delete to authenticated
using ((select public.is_admin()));

drop policy if exists "admins can insert events" on public.events;
create policy "admins can insert events"
on public.events for insert to authenticated
with check ((select public.is_admin()));

drop policy if exists "admins can update events" on public.events;
create policy "admins can update events"
on public.events for update to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "admins can delete events" on public.events;
create policy "admins can delete events"
on public.events for delete to authenticated
using ((select public.is_admin()));

drop policy if exists "admins can read all donation accounts" on public.donation_accounts;
create policy "admins can read all donation accounts"
on public.donation_accounts for select to authenticated
using ((select public.is_admin()));

drop policy if exists "admins can insert donation accounts" on public.donation_accounts;
create policy "admins can insert donation accounts"
on public.donation_accounts for insert to authenticated
with check ((select public.is_admin()));

drop policy if exists "admins can update donation accounts" on public.donation_accounts;
create policy "admins can update donation accounts"
on public.donation_accounts for update to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "admins can delete donation accounts" on public.donation_accounts;
create policy "admins can delete donation accounts"
on public.donation_accounts for delete to authenticated
using ((select public.is_admin()));

-- Pastikan sequence / identity dapat dipakai sesuai grants Data API.
grant select, insert, update, delete on public.service_requests to authenticated;
grant select, insert, update, delete on public.contact_messages to authenticated;
grant select, insert, update, delete on public.events to authenticated;
grant select, insert, update, delete on public.donation_accounts to authenticated;
grant select on public.admin_users to authenticated;
